name: Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-justjoinit-scraper:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1

    - name: Login to AWS
      run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 393861902470.dkr.ecr.eu-central-1.amazonaws.com

    - name: Build Docker Image
      run: docker build -t skilzzz-justjoinit-scraper -f Dockerfile.justjoinit-scraper .

    - name: Tag Docker Image
      run: docker tag skilzzz-justjoinit-scraper:latest 393861902470.dkr.ecr.eu-central-1.amazonaws.com/skilzzz-justjoinit-scraper:latest

    - name: Push Docker Image
      run: docker push 393861902470.dkr.ecr.eu-central-1.amazonaws.com/skilzzz-justjoinit-scraper:latest

